name: Build Matrix

on:
  workflow_dispatch:
    inputs:
      caller:
        description: 'The invoker of the workflow'
        required: false
        default: ''
  push:
    branches: ['main']

env:
  IMAGE_NAME: gabek/go-crosscompile

jobs:
  build-and-push-image:
    strategy:
      matrix:
        tag:
          - '1.25'
          # - '1.24'
          # - '1.23'
          # - '1.22'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Parameters
        id: params
        env:
          TAG: ${{ matrix.tag }}
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
          flavor: |
            latest=${{ matrix.tag == '1.25' }}
          tags: |
            type=sha,enable=true,priority=100,prefix=${{ matrix.tag }}-${{ steps.params.outputs.date }}--,suffix=,format=short
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
            DOCKER_TAG=${{ matrix.tag }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ matrix.tag }}
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
